using System.Collections.Generic;

namespace DeelTownCalculator
{
    public enum ItemType
    {
        Coal,
        Graphite,

        Copper,
        CopperBar,
        Iron,
        IronBar,
        SteelBar,
        Aluminium,
        AluminiumBar,
        Silver,
        SilverBar,
        Gold,
        GoldBar,
        Titanium,
        TitaniumBar,
        Platinum,

        SteelPlate,
        DiamondCutter,
        Motherboard,
        CopperNail,
        OpticFiber,
        AmberInsulation,
        DryIce,
        SolarPanel,
        GreenLaser,
        Wire,
        InsulatedWire,
        AmaberCharger,
        ElecticalEngine,
        AluminumBottle,
        Bomb,
        Gear,
        Battery,
        Lamp,
        Magnet,
        Compressor,
        Accumulator,
        SolidPropellant,
        Circuits,

        Uranium,
        TitaniumOre,
        Amber,
        PolishedAmber,
        Emerald,
        PolishedEmerald,
        Topaz,
        PolishedTopaz,
        Ruby,
        PolishedRuby,
        Sapphire,
        PolishedSappire,
        Amethyst,
        PolishedAmethyst,
        Diamond,
        PolishedDiamond,
        Alexandrite,
        PolishedAlexandrite,
        Obsidian,
        PolishedObsidian,

        EmeraldRing,
        AmberBracelet,
        MayaCalendar,
        Haircomb,
        ObsidianKnife,

        TreeSeed,
        Tree,
        LianaSeed,
        Liana,
        Rubber,
        GrapeSeed,
        Grape,
        Ethanol,

        Water,
        Oil,
        Sulfur,
        Sodium,
        Nitrogen,
        Helium3,
        Silicon,
        Glass,
        LabFlask,
        CleanWater,
        Hydrogen,
        Oxygen,
        GunPowder,
        SulfuricAcid,
        PlasticPlate,
        MagnetiteOre,
        DiethylEther,
        UraniumRod,
        PlasicPlate,
        TonixBomb,
        EnhancedHelium3,

        LiquidNitrogen
    }

    public class ItemDefines
    {
        public static readonly Dictionary<ItemType, int> SellingPrices = new Dictionary<ItemType, int>
        {
            {ItemType.Coal, 1},
            {ItemType.Copper, 2},
            {ItemType.Iron, 3},
            {ItemType.Amber, 4},
            {ItemType.Aluminium, 5},
            {ItemType.Silver, 7},
            {ItemType.Gold, 10},
            {ItemType.Emerald, 12},
            {ItemType.Platinum, 13},
            {ItemType.Topaz, 14},
            {ItemType.Ruby, 15},
            {ItemType.Sapphire, 16},
            {ItemType.Amethyst, 18},
            {ItemType.Diamond, 18},
            {ItemType.TitaniumOre, 19},
            {ItemType.Alexandrite, 19},
            {ItemType.Obsidian, 20},
            {ItemType.Uranium, 22},
            {ItemType.Helium3, 400},

            {ItemType.CopperBar, 25},
            {ItemType.IronBar, 40},
            {ItemType.AluminiumBar, 50},
            {ItemType.SteelBar, 180},
            {ItemType.SilverBar, 200},
            {ItemType.GoldBar, 250},
            {ItemType.LabFlask, 800},
            {ItemType.TitaniumBar, 3000},
            {ItemType.DiamondCutter, 5000},
            {ItemType.Motherboard, 17000},
            {ItemType.CopperNail, 7},
            {ItemType.OpticFiber, 10500},
            {ItemType.AmberInsulation, 125},
            {ItemType.DryIce, 140000},
            {ItemType.SolarPanel, 69000},
            {ItemType.Graphite, 15},
            {ItemType.GreenLaser, 400},
            {ItemType.Wire, 15},

            {ItemType.InsulatedWire, 750},
            {ItemType.AmaberCharger, 4},
            {ItemType.ElecticalEngine, 74500},
            {ItemType.AluminumBottle, 55},
            {ItemType.Bomb, 55500},
            {ItemType.Gear, 18500},
            {ItemType.Battery, 200},
            {ItemType.Lamp, 760},
            {ItemType.Compressor, 44000},
            {ItemType.Accumulator, 9000},
            {ItemType.SolidPropellant, 27000},
            {ItemType.Circuits, 2070},

            {ItemType.PolishedAmber, 70},
            {ItemType.PolishedEmerald, 160},
            {ItemType.PolishedTopaz, 200},
            {ItemType.PolishedSappire, 230},
            {ItemType.PolishedRuby, 250},
            {ItemType.PolishedAmethyst, 250},
            {ItemType.PolishedAlexandrite, 270},
            {ItemType.PolishedObsidian, 280},
            {ItemType.AmberBracelet, 280},

            {ItemType.PolishedDiamond, 300},
            {ItemType.EmeraldRing, 450}, // update price
            {ItemType.MayaCalendar, 6000}, // update price
            {ItemType.Haircomb, 14000}, // update price
            {ItemType.ObsidianKnife, 32000}, // update price

            {ItemType.Water, 5},
            {ItemType.Oil, 21},
            {ItemType.Sulfur, 100},
            {ItemType.Silicon, 100},
            {ItemType.Sodium, 100},
            {ItemType.Titanium, 260},
            {ItemType.Nitrogen, 300},
            {ItemType.Hydrogen, 400},
            {ItemType.Glass, 450},

            {ItemType.Oxygen, 900},
            {ItemType.CleanWater, 1200},
            {ItemType.GunPowder, 2500},
            {ItemType.SulfuricAcid, 3500},
            {ItemType.Rubber, 4000},
            {ItemType.Ethanol, 4200},
            {ItemType.LiquidNitrogen, 12500},
            {ItemType.MagnetiteOre, 12500},
            {ItemType.DiethylEther, 17000},

            {ItemType.UraniumRod, 17000},
            {ItemType.PlasticPlate, 40000},
            {ItemType.TonixBomb, 77500},
            {ItemType.EnhancedHelium3, 19000},

            {ItemType.TreeSeed, 10},
            {ItemType.Tree, 193},
            {ItemType.LianaSeed, 1000},
            {ItemType.GrapeSeed, 1200},
            {ItemType.Grape, 1500},
            {ItemType.Liana, 1700}
        };
    }
}